name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: checkout torah
        run: |
          git fetch --all
          git checkout gh-pages
          rm -rf ./* || true
          git clone https://github.com/kolodny/torah.git
          cd torah
          npm install

          git clone --filter=blob:none --no-checkout https://github.com/Sivan22/otzaria-library.git
          cd otzaria-library
          git sparse-checkout init --cone
          git sparse-checkout set links/ אוצריא/ 'books lists/ספריא/'
          git checkout HEAD
          cd ..

          node ./scripts/build-db.ts
          node ./scripts/slice-db.ts

          npm run build
          mv dist/* ..
          cd ..
          rm -rf torah
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy static site" || echo "No changes to commit"
          git push origin HEAD
