name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Custom sparse checkout
        run: |
          git clone https://github.com/kolodny/torah.git
          cd torah
          npm install
          npm run build
          mv dist/* ..
          cd ..
          rm -rf torah
