name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Checkout torah repo
        run: |
          git checkout -b gh-pages
          rm -rf ./* || true
          git clone https://github.com/kolodny/torah.git
          cd torah
          npm install

      - name: Checkout data repo
        run: |
          cd torah

          git clone --filter=blob:none --no-checkout https://github.com/Sefaria/Sefaria-Export.git
          cd Sefaria-Export
          git sparse-checkout init --cone
          git sparse-checkout set json/ schemas/ links/ table_of_contents.json
          git checkout HEAD

      - name: Build db
        run: |
          cd torah
          node ./scripts/build-db.ts

      - name: Split db
        run: |
          cd torah
          node ./scripts/slice-db.ts

      - name: Build static site
        run: |
          cd torah
          npm run build

      - name: Push static site
        run: |
          cd torah
          mv dist/* ..
          cd ..
          rm -rf torah
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy static site" || echo "No changes to commit"
          git push origin HEAD -f
